### PR TITLE
Makefile fixes

### PR DESCRIPTION
**Pull request by xvitaly**
* Respect already defined by build environment CFLAGS.
* Added base LDFLAGS (will be overriden via build environment).
* Fixed incorrect chmod on shared library and icons.
* Preserve timestamps on installed files.

### CODE REVIEW

**Comment by xvitaly** [comment]
Shared libraries must have 0755 chmod, regular files - 0644.

**Comment by richvdh** [comment]
> Shared libraries must have 0755 chmod, regular files - 0644.

not afaik.

**Comment by xvitaly** [comment]
> not afaik

**Comment by xvitaly** [comment]
And about timestamps: https://reproducible-builds.org/docs/timestamps/

**Comment by richvdh** [comment]
> > not afaik
>
> https://fedoraproject.org/wiki/Packaging:Guidelines

where?

**Comment by richvdh** [comment]
> And about timestamps (adding `-p` parameter): https://reproducible-builds.org/docs/timestamps/

again, where? that's about builds, not installation?

**Comment by richvdh** [comment]
> > And about timestamps (adding `-p` parameter): https://reproducible-builds.org/docs/timestamps/
>
> again, where? that's about builds, not installation?

Indeed, it seems to say the opposite: that you should *not* copy timestamps.

Your changes may well be correct, but please try to explain what you're doing in more than one word. Linking to a big page and expecting me to figure it out isn't terribly helpful.

**Pull request closed without merging**
