### PR TITLE
Add an option to get markdown, not HTML

### LINKED ISSUE #116: Option to get markdown, not HTML
**Is your feature request related to a problem? Please describe.**
I'm using purple-matrix via bitlbee and if people use the `[Link](http://a.com)` markup to link a URL, currently the plain text output is just `Link`, dropping the actual URL.

**Describe the solution you'd like**
It would be nice to have an option that prefers the original markdown of the message, which has the URL instead.

**Describe alternatives you've considered**
I guess the actual HTML -> plaintext conversion is done by bitlbee, so that could convert HTML back to markdown... but that's quite some work, and going via HTML just to convert back sounds pointless.

**Additional context**
I'm happy to send a PR that introduces a build-time option like MATRIX_NO_E2E for this, just wanted to santiy check the idea before doing so.

I imagine that it's rare the same binary is used by both pidgin and bitlbee at the same time and a build-time option is a matter of #ifdef in matrix-room.c, it seems to me.

What do you think? Thanks.

### PR DESCRIPTION
**Pull request by vmiklos**
Fixes #116

### CODE REVIEW

**Comment by vmiklos** [comment]
@richvdh could you please take a look? Thanks :-)

**Comment by EionRobb** [comment]
libpurple expects to receive xhtml from prpls, not markdown.  This compile-time setting becomes a problem for packaging too, because then you can't have a single shared library used for any libpurple client/UI, as the behaviour at runtime is ambiguous.

Please don't merge this PR.

**Comment by penguin42** [comment]
Looking at the report; so what does bittlebee do for other plugins when they provide URLs (I don't use bittlebee myself)?

**Comment by vmiklos** [comment]
> libpurple expects to receive xhtml from prpls, not markdown. This compile-time setting becomes a problem for packaging too, because then you can't have a single shared library used for any libpurple client/UI, as the behaviour at runtime is ambiguous.

I see, I didn't consider the packaging aspect. Would it help if this is turned into a runtime setting, similar to `home_server`?

> Looking at the report; so what does bittlebee do for other plugins when they provide URLs (I don't use bittlebee myself)?

bitlbee simply strips away html from incoming messages. This is reasonable when that's the only format produced by the protocol (e.g. MSN back in the day). Matrix is special as the original markdown (which is quite readable in a text-based client) is also an option. matrix-ircd (and other similar tools like matterircd) present the original markdown to users, the PR tries to improve purple-matrix to do the same.

Sure, you could say that bitlbee should turn html back to markdown, it's just a little silly to do so when the source of that HTML was markdown in the first place. :-)

**Comment by penguin42** [comment]
> > libpurple expects to receive xhtml from prpls, not markdown. This compile-time setting becomes a problem for packaging too, because then you can't have a single shared library used for any libpurple client/UI, as the behaviour at runtime is ambiguous.
> 
> I see, I didn't consider the packaging aspect. Would it help if this is turned into a runtime setting, similar to `home_server`?

I think that would solve it from a packaging point of view - and I'd go with whatever Eion's recommendation is here.

> > Looking at the report; so what does bittlebee do for other plugins when they provide URLs (I don't use bittlebee myself)?
> 
> bitlbee simply strips away html from incoming messages. This is reasonable when that's the only format produced by the protocol (e.g. MSN back in the day). Matrix is special as the original markdown (which is quite readable in a text-based client) is also an option. matrix-ircd (and other similar tools like matterircd) present the original markdown to users, the PR tries to improve purple-matrix to do the same.
> 
> Sure, you could say that bitlbee should turn html back to markdown, it's just a little silly to do so when the source of that HTML was markdown in the first place. :-)

yeh, although I guess html is the defined interface here.

**Comment by vmiklos** [comment]
Please take a look, I replaced the build-time option with a runtime option as you requested. Thanks!

**Comment by vmiklos** [comment]
@EionRobb @penguin42 ping, could you please review the above? I addressed the build-time / packaging concern you had there, I hope. :-) Thanks.

**Review by penguin42 — APPROVED** [review]
Seems OK, and doesn't break pidgin in either state that I can see

**Pull request merged**
