### PR TITLE
Handle media messages (m.video, m.audio, m.file)

### PR DESCRIPTION
**Pull request by radiocane**
For messages of types m.video, m.audio and m.file, send to the user the fallback text, mime type and size (if available), and a link to the content.

### CODE REVIEW

**Comment by radiocane** [comment]
Yes, we can shrink this, but I'd say renaming and adding the msg_type parameter is not enough: the thumbnail handling is different, also the proposed handle_incoming_media always writes a chat message with a URL, while the current handle_incoming_image only when img download fails.
Anyway I'll work on it tomorrow :)

**Comment by radiocane** [comment]
On 2017-11-11 23:13, Dave Gilbert wrote:
> Have you considered that you might want to change this into
> ReceiveMediaData and use this for all media types?

I'm not sure about what you mean with "all media".
Before coding, I'd prefer to reach consensus on what to do.
I'd like to remove duplication with a single _handle_incoming_media 
function which will handle m.image, m.video, m.audio and m.file.
The funcion would *always* print a chat message with the complete 
download url, with info if available.
m.audio are not supposed to have thumbnails, so for m.audio the handling 
would stop here.
For m.video and m.file, if thumbnail size is smaller than a 
user-configurable value purple_max_media_size, download the thumbnail.
For m.image, if size is smaller than purple_max_media_size, download the 
image, else if thumbnail_size < purple_max_media_size, download 
thumbnail, else ask the server to generate a thumbnail 
(matrix_api_download_thumb).
Does this make sense? what do you think?

**Comment by penguin42** [comment]
Hi,
  I've gone through this and the final thing looks pretty good - but it could do with flattening down; so if you can merge the 'Remove _handle_incoming_image' down into the earlier commits, so we don't end up creating duplication and then immediately removing it, I think we're good to go.

**Comment by radiocane** [comment]
Ok, this was my first flattening; is it ok?

**Comment by penguin42** [comment]
I've merged it; I would have actually split it a bit differently; e.g. the increase of media size, the split out of get_download_url could have been separate small commits.  But anyway, thanks!

**Comment by radiocane** [comment]
Thank you :)

**Pull request merged**
