### PR TITLE
Possible fix Sync crash #125

### PR DESCRIPTION
**Pull request by axet**

### CODE REVIEW

**Comment by richvdh** [comment]
> Possible fix Sync crash

what does this mean?

I don't have much time to maintain this repository: please help me out by explaining what your PR is doing.

**Comment by axet** [comment]
It either: memory corruption or using freed connection pointer. I add this check and it seems crashing is gone. So, can be just bad luck. Right now I'm not 100% sure this is correct fix.

**Comment by richvdh** [comment]
OK let us know when you think this might be ready for merging. I'll mark it as draft for now.

**Comment by axet** [comment]
it is unclear what caused a crash. it stop crashing with or without a patch.

**Pull request closed without merging**
